### ISSUE TITLE
centos7.9 mvn package Could not create a customized JRE due to JDK version is 1.8.0_322

### ISSUE THREAD

**Issue by kk678** [rememberber/MooInfo#13]
CentOS Linux release 7.9.2009 (Core)
code commit 01813997a31b5029cf5a3da9b480b7a0cc75eb32

mvn package

[INFO] Copying jfreechart-1.5.3.jar to /root/MooInfo/target/MooInfo/libs/jfreechart-1.5.3.jar
[INFO]     Dependencies copied to /root/MooInfo/target/MooInfo/libs!
[INFO]     
[INFO]     Creating runnable JAR...
[INFO]     Runnable jar created in /root/MooInfo/target/MooInfo-1.1.1-runnable.jar!
[INFO]     
[INFO]     Bundling JRE ... with /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-1.el7_9.x86_64/jre
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.752s
[INFO] Finished at: Thu Mar 03 13:54:29 PST 2022
[INFO] Final Memory: 26M/338M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.6.3:package (bundling-for-windows) on project MooInfo: Could not create a customized JRE due to JDK version is 1.8.0_322. Must use jrePath property to specify JRE location to be embedded -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by rememberber** [comment]
Need Java 17, or turn off the "customized JRE" option in javapackager maven plugin
