### ISSUE TITLE
在windows系统下， 用idea 启动显示窗体程序未响应。但是下载windows包运行就没什么问题

### ISSUE THREAD

**Issue by zerodayZHOUXUTIAN** [rememberber/MooInfo#3]

**Comment by rememberber** [comment]
JDK 是什么版本？
有详细的报错信息或者截图吗？

**Comment by zerodayZHOUXUTIAN** [comment]
系统: Windows 10 家庭中文版
idea版本: intellij Ultimate 2020.3.1
JDK版本: 1.8.0_91
![image](https://user-images.githubusercontent.com/30335316/146509710-2530776d-4431-41c4-89b7-19a5d9c20630.png)
窗体显示未响应

**Comment by zerodayZHOUXUTIAN** [comment]
![image](https://user-images.githubusercontent.com/30335316/146509813-440375ff-a2b8-44e0-94c2-73d17461052f.png)

**Comment by rememberber** [comment]
@zerodayZHOUXUTIAN 用JDK17试试

**Comment by zerodayZHOUXUTIAN** [comment]
> 

升级到17，确实没问题了. 不过这个要求的版本也太高了叭
